[package]
name = "monkey"
version = "0.2.0"
authors = ["AlphaKeks <alphakeks@dawn.sh>"]
edition = "2021"
readme = "./README.md"
license-file = "./LICENSE"
publish = false

[dependencies]

[dev-dependencies]
